package com.accenture.bby.sdp.utl.audit;

public enum Action {
	SDP_NEW_ACTIVATION(1),
	SDP_NEW_CANCELLATION(2),
	VENDOR_NEW_ACTIVATION(3),
	VENDOR_NEW_CANCELLATION(4),
	VENDOR_NEW_RENEWAL(5),
	VENDOR_NEW_MODIFY_STATUS(6),
	VENDOR_NEW_ACTIVATION_OVERRIDE(7),
	VENDOR_NEW_CANCELLATION_OVERRIDE(8),
	VENDOR_NEW_RENEWAL_OVERRIDE(9),
	VENDOR_NEW_MODIFY_STATUS_OVERRIDE(10),
	VENDOR_RETRY_ACTIVATION(11),
	VENDOR_RETRY_CANCELLATION(12),
	VENDOR_RETRY_RENEWAL(13),
	VENDOR_RETRY_MODIFY_STATUS(14),
	COMMSAT_REFLOW_EMAIL(15),
	KCB_LOAD_KEYCODES(16),
	UPDATED_KCB_KEYCODE_LOAD(17),
	LOOKUP_SUBSCRIPTION_DATA(18),
	LOOKUP_VENDOR_DATA(19),
	MONITORING_PAUSED_QUEUE_CONSUMPTION(20),
	MONITORING_RESUMED_QUEUE_CONSUMPTION(21),
	REFRESHED_SDPCONFIG(22),
	SDP_NEW_REACTIVATION(23),
	UPDATED_PREORDER_SCHEDULE(24),
	DELETED_PREORDER_SCHEDULE(25),
	CREATED_PREORDER_SCHEDULE(26),
	CREATED_VENDOR_CONFIGURATION(27),
	UPDATED_VENDOR_CONFIGURATION(28),
	CREATED_KCB_VENDOR_CONFIGURATION(29),
	UPDATED_KCB_VENDOR_CONFIGURATION(30),
	CREATED_CATALOG_CONFIGURATION(31),
	UPDATED_CATALOG_CONFIGURATION(32),
	CREATED_VENDOR_CODE_CONFIGURATION(33),
	UPDATED_VENDOR_CODE_CONFIGURATION(34),
	CREATED_KCB_PRODUCT_CONFIGURATION(35),
	UPDATED_KCB_PRODUCT_CONFIGURATION(36),
	DELETED_KCB_KEYCODE_LOAD(37),
	SDP_NEW_ADJUSTACTIVATION(38),
	ECC_RESEND_EMAIL(39),
	ECC_ORDER_LOOKUP(40);
	
	private int fieldTypeId;
	
	private Action(final int fieldTypeId) {
		this.fieldTypeId = fieldTypeId;
	}
	
	public int getFieldTypeId() {
		return fieldTypeId;
	}
}
